from io import BytesIO

from flask import Blueprint, send_file
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import (
    ParagraphStyle,
    getSampleStyleSheet,
)
from reportlab.lib.units import mm
from reportlab.platypus import (
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from ..enums import ClearanceStatus, UserRole
from ..extensions import db
from ..models import Appointment, Clearance, CounselingCase
from ..utils import audit, current_user, error, roles_required
from .cases import can_access_case


reports_bp = Blueprint("reports", __name__)


# =========================================================
# SHARED / GENERIC PDF
# Used by Case Summary and Clearance Certificate for now.
# =========================================================

def make_pdf(title, rows, confidentiality=None):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
    )

    styles = getSampleStyleSheet()

    story = [
        Paragraph(
            "UNIVERSITY GUIDANCE & COUNSELING",
            styles["Heading2"],
        ),
        Spacer(1, 5 * mm),
        Paragraph(
            title,
            styles["Title"],
        ),
    ]

    if confidentiality:

        story += [
            Spacer(1, 3 * mm),
            Paragraph(
                confidentiality,
                styles["Italic"],
            ),
        ]

    story += [
        Spacer(1, 8 * mm)
    ]

    data = [
        [
            Paragraph(
                f"<b>{label}</b>",
                styles["BodyText"],
            ),
            Paragraph(
                str(value or "—"),
                styles["BodyText"],
            ),
        ]
        for label, value in rows
    ]

    table = Table(
        data,
        colWidths=[
            55 * mm,
            105 * mm,
        ],
    )

    table.setStyle(
        TableStyle([
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "TOP",
            ),
            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.4,
                colors.HexColor("#B9C4CC"),
            ),
            (
                "BACKGROUND",
                (0, 0),
                (0, -1),
                colors.HexColor("#E9F5F2"),
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                5,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                5,
            ),
        ])
    )

    story += [
        table,
        Spacer(1, 18 * mm),
        Paragraph(
            "Generated by the University Guidance & Counseling Management System",
            styles["Italic"],
        ),
    ]

    doc.build(story)

    buffer.seek(0)

    return buffer


# =========================================================
# DATE / TIME FORMATTERS
# =========================================================

def format_document_date(value):

    if not value:
        return "—"

    return value.strftime(
        "%B %d, %Y"
    )


def format_document_time(value):

    if not value:
        return "—"

    # %I gives 12-hour time.
    # lstrip removes the leading zero from values such as 09:00 AM.
    return value.strftime(
        "%I:%M %p"
    ).lstrip("0")


# =========================================================
# FORMAL APPOINTMENT CONFIRMATION PDF
# =========================================================

def make_appointment_confirmation_pdf(appointment):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=22 * mm,
        leftMargin=22 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title="Guidance Appointment Confirmation Slip",
        author="University Guidance & Counseling Office",
    )

    # -----------------------------------------------------
    # COLORS
    # -----------------------------------------------------

    purple = colors.HexColor("#6F42C1")
    dark_purple = colors.HexColor("#4F2B78")
    light_purple = colors.HexColor("#F4EEFB")

    dark_text = colors.HexColor("#2F2935")
    gray_text = colors.HexColor("#6F6875")
    border = colors.HexColor("#DDD6E5")

    reminder_background = colors.HexColor("#F8F5FB")

    # -----------------------------------------------------
    # STYLES
    # -----------------------------------------------------

    styles = getSampleStyleSheet()

    office_title_style = ParagraphStyle(
        "AppointmentOfficeTitle",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        textColor=dark_text,
        spaceAfter=2,
    )

    office_subtitle_style = ParagraphStyle(
        "AppointmentOfficeSubtitle",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        textColor=gray_text,
    )

    document_title_style = ParagraphStyle(
        "AppointmentDocumentTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=16,
        leading=20,
        alignment=TA_CENTER,
        textColor=dark_purple,
        spaceAfter=0,
    )

    section_title_style = ParagraphStyle(
        "AppointmentSectionTitle",
        parent=styles["Heading3"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=11,
        textColor=dark_purple,
        spaceAfter=0,
    )

    label_style = ParagraphStyle(
        "AppointmentLabel",
        parent=styles["BodyText"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=gray_text,
    )

    value_style = ParagraphStyle(
        "AppointmentValue",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=13,
        textColor=dark_text,
    )

    status_style = ParagraphStyle(
        "AppointmentStatus",
        parent=value_style,
        fontName="Helvetica-Bold",
        textColor=dark_purple,
    )

    reminder_title_style = ParagraphStyle(
        "AppointmentReminderTitle",
        parent=styles["BodyText"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=dark_purple,
        spaceAfter=4,
    )

    reminder_text_style = ParagraphStyle(
        "AppointmentReminderText",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12,
        textColor=dark_text,
    )

    signature_label_style = ParagraphStyle(
        "AppointmentSignature",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=8,
        leading=10,
        alignment=TA_CENTER,
        textColor=gray_text,
    )

    footer_style = ParagraphStyle(
        "AppointmentFooter",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=7.5,
        leading=10,
        alignment=TA_CENTER,
        textColor=gray_text,
    )

    # -----------------------------------------------------
    # HEADER
    # Plain "GC" logo — no leaf/icon graphic.
    # -----------------------------------------------------

    gc_logo = Table(
        [
            [
                Paragraph(
                    "<b>GC</b>",
                    ParagraphStyle(
                        "GCLogoText",
                        parent=styles["BodyText"],
                        fontName="Helvetica-Bold",
                        fontSize=19,
                        leading=22,
                        alignment=TA_CENTER,
                        textColor=colors.white,
                    ),
                )
            ]
        ],
        colWidths=[
            19 * mm
        ],
        rowHeights=[
            19 * mm
        ],
    )

    gc_logo.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                purple,
            ),
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE",
            ),
            (
                "ALIGN",
                (0, 0),
                (-1, -1),
                "CENTER",
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.8,
                purple,
            ),
        ])
    )

    office_text = [
        Paragraph(
            "UNIVERSITY GUIDANCE &amp; COUNSELING OFFICE",
            office_title_style,
        ),
        Paragraph(
            "Guidance and Counseling Management System",
            office_subtitle_style,
        ),
    ]

    header = Table(
        [
            [
                gc_logo,
                office_text,
            ]
        ],
        colWidths=[
            24 * mm,
            140 * mm,
        ],
    )

    header.setStyle(
        TableStyle([
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE",
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                0,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                0,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                0,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                0,
            ),
        ])
    )

    # -----------------------------------------------------
    # HEADER DIVIDER
    # -----------------------------------------------------

    divider = Table(
        [[""]],
        colWidths=[
            166 * mm
        ],
        rowHeights=[
            1.2 * mm
        ],
    )

    divider.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                purple,
            ),
            (
                "LINEBELOW",
                (0, 0),
                (-1, -1),
                0,
                purple,
            ),
        ])
    )

    # -----------------------------------------------------
    # STUDENT INFORMATION
    # -----------------------------------------------------

    student_name = (
        appointment.student.to_dict()["full_name"]
    )

    student_number = (
        appointment.student.student_number
    )

    date_requested = (
        format_document_date(
            appointment.created_at
        )
    )

    student_section_title = Table(
        [
            [
                Paragraph(
                    "STUDENT INFORMATION",
                    section_title_style,
                )
            ]
        ],
        colWidths=[
            166 * mm
        ],
    )

    student_section_title.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                light_purple,
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.5,
                border,
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                6,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                6,
            ),
        ])
    )

    student_data = [
        [
            Paragraph(
                "Student Name",
                label_style,
            ),
            Paragraph(
                str(student_name or "—"),
                value_style,
            ),
        ],
        [
            Paragraph(
                "Student Number",
                label_style,
            ),
            Paragraph(
                str(student_number or "—"),
                value_style,
            ),
        ],
        [
            Paragraph(
                "Date Requested",
                label_style,
            ),
            Paragraph(
                date_requested,
                value_style,
            ),
        ],
    ]

    student_table = Table(
        student_data,
        colWidths=[
            43 * mm,
            123 * mm,
        ],
    )

    student_table.setStyle(
        TableStyle([
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "TOP",
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.5,
                border,
            ),
            (
                "INNERGRID",
                (0, 0),
                (-1, -1),
                0.35,
                border,
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
        ])
    )

    # -----------------------------------------------------
    # APPOINTMENT DETAILS
    # -----------------------------------------------------

    appointment_date = (
        format_document_date(
            appointment.starts_at
        )
    )

    appointment_time = (
        f"{format_document_time(appointment.starts_at)}"
        f" - "
        f"{format_document_time(appointment.ends_at)}"
    )

    counselor_name = (
        appointment.counselor.to_dict()["full_name"]
    )

    room_name = (
        appointment.room.name
        if appointment.room
        else "To be assigned"
    )

    purpose = (
        appointment.purpose or "—"
    )

    status = (
        appointment.status.value
        if appointment.status
        else "—"
    )

    appointment_section_title = Table(
        [
            [
                Paragraph(
                    "APPOINTMENT DETAILS",
                    section_title_style,
                )
            ]
        ],
        colWidths=[
            166 * mm
        ],
    )

    appointment_section_title.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                light_purple,
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.5,
                border,
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                6,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                6,
            ),
        ])
    )

    appointment_data = [
        [
            Paragraph(
                "Appointment Date",
                label_style,
            ),
            Paragraph(
                appointment_date,
                value_style,
            ),
        ],
        [
            Paragraph(
                "Appointment Time",
                label_style,
            ),
            Paragraph(
                appointment_time,
                value_style,
            ),
        ],
        [
            Paragraph(
                "Assigned Counselor",
                label_style,
            ),
            Paragraph(
                str(counselor_name or "—"),
                value_style,
            ),
        ],
        [
            Paragraph(
                "Guidance Room",
                label_style,
            ),
            Paragraph(
                str(room_name),
                value_style,
            ),
        ],
        [
            Paragraph(
                "Purpose",
                label_style,
            ),
            Paragraph(
                str(purpose),
                value_style,
            ),
        ],
        [
            Paragraph(
                "Status",
                label_style,
            ),
            Paragraph(
                str(status).replace(
                    "_",
                    " "
                ).title(),
                status_style,
            ),
        ],
    ]

    appointment_table = Table(
        appointment_data,
        colWidths=[
            43 * mm,
            123 * mm,
        ],
    )

    appointment_table.setStyle(
        TableStyle([
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "TOP",
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.5,
                border,
            ),
            (
                "INNERGRID",
                (0, 0),
                (-1, -1),
                0.35,
                border,
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
        ])
    )

    # -----------------------------------------------------
    # IMPORTANT REMINDER
    # -----------------------------------------------------

    reminder = Table(
        [
            [
                Paragraph(
                    "IMPORTANT REMINDER",
                    reminder_title_style,
                ),
            ],
            [
                Paragraph(
                    "Please present this confirmation slip when reporting "
                    "to the Guidance and Counseling Office. Students are "
                    "encouraged to arrive a few minutes before the scheduled "
                    "appointment time.",
                    reminder_text_style,
                ),
            ],
        ],
        colWidths=[
            166 * mm
        ],
    )

    reminder.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                reminder_background,
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.7,
                purple,
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                10,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                10,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
        ])
    )

    # -----------------------------------------------------
    # SIGNATURE AREA
    # -----------------------------------------------------

    signature_line = (
        "____________________________"
    )

    signatures = Table(
        [
            [
                Paragraph(
                    signature_line,
                    signature_label_style,
                ),
                Paragraph(
                    signature_line,
                    signature_label_style,
                ),
            ],
            [
                Paragraph(
                    "Student Signature",
                    signature_label_style,
                ),
                Paragraph(
                    "Counselor / Authorized Staff",
                    signature_label_style,
                ),
            ],
        ],
        colWidths=[
            83 * mm,
            83 * mm,
        ],
    )

    signatures.setStyle(
        TableStyle([
            (
                "ALIGN",
                (0, 0),
                (-1, -1),
                "CENTER",
            ),
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "TOP",
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                6,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                6,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                2,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                2,
            ),
        ])
    )

    # -----------------------------------------------------
    # FOOTER
    # -----------------------------------------------------

    footer = Paragraph(
        "This is a system-generated document from the "
        "University Guidance &amp; Counseling Management System.",
        footer_style,
    )

    # -----------------------------------------------------
    # BUILD DOCUMENT
    # -----------------------------------------------------

    story = [
        header,

        Spacer(
            1,
            5 * mm,
        ),

        divider,

        Spacer(
            1,
            8 * mm,
        ),

        Paragraph(
            "GUIDANCE APPOINTMENT CONFIRMATION SLIP",
            document_title_style,
        ),

        Spacer(
            1,
            9 * mm,
        ),

        KeepTogether([
            student_section_title,
            student_table,
        ]),

        Spacer(
            1,
            7 * mm,
        ),

        KeepTogether([
            appointment_section_title,
            appointment_table,
        ]),

        Spacer(
            1,
            8 * mm,
        ),

        reminder,

        Spacer(
            1,
            18 * mm,
        ),

        signatures,

        Spacer(
            1,
            13 * mm,
        ),

        divider,

        Spacer(
            1,
            4 * mm,
        ),

        footer,
    ]

    doc.build(
        story
    )

    buffer.seek(0)

    return buffer

# =========================================================
# APPOINTMENT CONFIRMATION SLIP
# =========================================================

@reports_bp.get(
    "/reports/appointments/<int:appointment_id>/confirmation.pdf"
)
@roles_required(
    UserRole.STUDENT,
    UserRole.COUNSELOR,
    UserRole.HEAD_COUNSELOR,
    UserRole.ADMIN,
    UserRole.STAFF,
)
def appointment_confirmation(appointment_id):

    appointment = db.session.get(
        Appointment,
        appointment_id,
    )

    user = current_user()

    if not appointment:

        return error(
            "Appointment not found.",
            404,
            "not_found",
        )

    participant = (
        user.role in {
            UserRole.HEAD_COUNSELOR,
            UserRole.ADMIN,
            UserRole.STAFF,
        }
    )

    participant |= (
        user.role == UserRole.STUDENT
        and appointment.student_id
        == user.student_profile.id
    )

    participant |= (
        user.role == UserRole.COUNSELOR
        and appointment.counselor_id
        == user.counselor_profile.id
    )

    if not participant:

        return error(
            "You do not have access to this appointment.",
            403,
            "forbidden",
        )

    audit(
        "APPOINTMENT_SLIP_GENERATED",
        "appointment",
        appointment.id,
        user.id,
    )

    db.session.commit()

    pdf = make_appointment_confirmation_pdf(
        appointment
    )

    return send_file(
        pdf,
        mimetype="application/pdf",
        as_attachment=True,
        download_name=(
            "guidance-appointment-confirmation.pdf"
        ),
    )

def make_case_summary_pdf(case):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=22 * mm,
        leftMargin=22 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title="Confidential Case Summary Slip",
        author="University Guidance & Counseling Office",
    )

    # -----------------------------------------------------
    # COLORS
    # -----------------------------------------------------

    purple = colors.HexColor("#6F42C1")
    dark_purple = colors.HexColor("#4F2B78")
    light_purple = colors.HexColor("#F4EEFB")

    dark_text = colors.HexColor("#2F2935")
    gray_text = colors.HexColor("#6F6875")
    border = colors.HexColor("#DDD6E5")
    notice_background = colors.HexColor("#F8F5FB")

    # -----------------------------------------------------
    # STYLES
    # -----------------------------------------------------

    styles = getSampleStyleSheet()

    office_title_style = ParagraphStyle(
        "CaseOfficeTitle",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        textColor=dark_text,
        spaceAfter=2,
    )

    office_subtitle_style = ParagraphStyle(
        "CaseOfficeSubtitle",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        textColor=gray_text,
    )

    document_title_style = ParagraphStyle(
        "CaseDocumentTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=16,
        leading=20,
        alignment=TA_CENTER,
        textColor=dark_purple,
        spaceAfter=0,
    )

    document_subtitle_style = ParagraphStyle(
        "CaseDocumentSubtitle",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        alignment=TA_CENTER,
        textColor=gray_text,
    )

    section_title_style = ParagraphStyle(
        "CaseSectionTitle",
        parent=styles["Heading3"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=11,
        textColor=dark_purple,
        spaceAfter=0,
    )

    label_style = ParagraphStyle(
        "CaseLabel",
        parent=styles["BodyText"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=gray_text,
    )

    value_style = ParagraphStyle(
        "CaseValue",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=13,
        textColor=dark_text,
    )

    emphasized_value_style = ParagraphStyle(
        "CaseEmphasizedValue",
        parent=value_style,
        fontName="Helvetica-Bold",
        textColor=dark_purple,
    )

    notice_title_style = ParagraphStyle(
        "CaseNoticeTitle",
        parent=styles["BodyText"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=dark_purple,
        spaceAfter=4,
    )

    notice_text_style = ParagraphStyle(
        "CaseNoticeText",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12,
        textColor=dark_text,
        alignment=TA_JUSTIFY,
    )

    signature_style = ParagraphStyle(
        "CaseSignature",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=8,
        leading=10,
        alignment=TA_CENTER,
        textColor=gray_text,
    )

    footer_style = ParagraphStyle(
        "CaseFooter",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=7.5,
        leading=10,
        alignment=TA_CENTER,
        textColor=gray_text,
    )

    # -----------------------------------------------------
    # HEADER
    # -----------------------------------------------------

    gc_logo = Table(
        [[
            Paragraph(
                "<b>GC</b>",
                ParagraphStyle(
                    "CaseGCLogo",
                    parent=styles["BodyText"],
                    fontName="Helvetica-Bold",
                    fontSize=19,
                    leading=22,
                    alignment=TA_CENTER,
                    textColor=colors.white,
                ),
            )
        ]],
        colWidths=[19 * mm],
        rowHeights=[19 * mm],
    )

    gc_logo.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                purple,
            ),
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE",
            ),
            (
                "ALIGN",
                (0, 0),
                (-1, -1),
                "CENTER",
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.8,
                purple,
            ),
        ])
    )

    office_text = [
        Paragraph(
            "UNIVERSITY GUIDANCE &amp; COUNSELING OFFICE",
            office_title_style,
        ),
        Paragraph(
            "Guidance and Counseling Management System",
            office_subtitle_style,
        ),
    ]

    header = Table(
        [[gc_logo, office_text]],
        colWidths=[
            24 * mm,
            140 * mm,
        ],
    )

    header.setStyle(
        TableStyle([
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE",
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                0,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                0,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                0,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                0,
            ),
        ])
    )

    divider = Table(
        [[""]],
        colWidths=[166 * mm],
        rowHeights=[1.2 * mm],
    )

    divider.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                purple,
            ),
        ])
    )

    # -----------------------------------------------------
    # CASE INFORMATION
    # -----------------------------------------------------

    pseudonym = f"STUDENT-{case.student_id:05d}"

    opened_date = (
        format_document_date(case.opened_at)
        if case.opened_at
        else "—"
    )

    closed_date = (
        format_document_date(case.closed_at)
        if case.closed_at
        else "Open"
    )

    counselor_name = (
        case.counselor.to_dict()["full_name"]
        if case.counselor
        else "—"
    )

    priority = (
        case.priority.value
        if case.priority
        else "—"
    )

    status = (
        case.status.value
        if case.status
        else "—"
    )

    case_section_title = Table(
        [[
            Paragraph(
                "CASE INFORMATION",
                section_title_style,
            )
        ]],
        colWidths=[166 * mm],
    )

    case_section_title.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                light_purple,
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.5,
                border,
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                6,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                6,
            ),
        ])
    )

    case_data = [
        [
            Paragraph("Case Number", label_style),
            Paragraph(
                str(case.case_number or "—"),
                emphasized_value_style,
            ),
        ],
        [
            Paragraph("Student Pseudonym", label_style),
            Paragraph(
                pseudonym,
                emphasized_value_style,
            ),
        ],
        [
            Paragraph("Category", label_style),
            Paragraph(
                str(case.category or "—"),
                value_style,
            ),
        ],
        [
            Paragraph("Priority", label_style),
            Paragraph(
                str(priority).replace("_", " ").title(),
                value_style,
            ),
        ],
        [
            Paragraph("Case Status", label_style),
            Paragraph(
                str(status).replace("_", " ").title(),
                emphasized_value_style,
            ),
        ],
        [
            Paragraph("Assigned Counselor", label_style),
            Paragraph(
                str(counselor_name),
                value_style,
            ),
        ],
        [
            Paragraph("Date Opened", label_style),
            Paragraph(
                opened_date,
                value_style,
            ),
        ],
        [
            Paragraph("Date Closed", label_style),
            Paragraph(
                closed_date,
                value_style,
            ),
        ],
    ]

    case_table = Table(
        case_data,
        colWidths=[
            43 * mm,
            123 * mm,
        ],
    )

    case_table.setStyle(
        TableStyle([
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "TOP",
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.5,
                border,
            ),
            (
                "INNERGRID",
                (0, 0),
                (-1, -1),
                0.35,
                border,
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                5,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                5,
            ),
        ])
    )

    # -----------------------------------------------------
    # CONFIDENTIALITY NOTICE
    # -----------------------------------------------------

    confidentiality_notice = Table(
        [
            [
                Paragraph(
                    "CONFIDENTIALITY NOTICE",
                    notice_title_style,
                )
            ],
            [
                Paragraph(
                    "This document is a pseudonymized case summary intended "
                    "for authorized Guidance and Counseling personnel only. "
                    "The student's identifying information is excluded from "
                    "this report. Confidential progress-note contents and "
                    "session details are not included.",
                    notice_text_style,
                )
            ],
        ],
        colWidths=[166 * mm],
    )

    confidentiality_notice.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                notice_background,
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.7,
                purple,
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                10,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                10,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
        ])
    )

    # -----------------------------------------------------
    # SIGNATURE
    # -----------------------------------------------------

    signatures = Table(
        [
            [
                "",
                Paragraph(
                    "____________________________",
                    signature_style,
                ),
            ],
            [
                "",
                Paragraph(
                    "Counselor / Authorized Personnel",
                    signature_style,
                ),
            ],
        ],
        colWidths=[
            83 * mm,
            83 * mm,
        ],
    )

    # -----------------------------------------------------
    # FOOTER
    # -----------------------------------------------------

    footer = Paragraph(
        "CONFIDENTIAL — System-generated document from the "
        "University Guidance &amp; Counseling Management System.",
        footer_style,
    )

    # -----------------------------------------------------
    # BUILD - ONE PAGE
    # -----------------------------------------------------

    story = [
        header,

        Spacer(1, 3 * mm),

        divider,

        Spacer(1, 5 * mm),

        Paragraph(
            "CONFIDENTIAL CASE SUMMARY SLIP",
            document_title_style,
        ),

        Spacer(1, 1.5 * mm),

        Paragraph(
            "Pseudonymized Case Record",
            document_subtitle_style,
        ),

        Spacer(1, 5 * mm),

        KeepTogether([
            case_section_title,
            case_table,
        ]),

        Spacer(1, 5 * mm),

        confidentiality_notice,

        Spacer(1, 9 * mm),

        signatures,

        Spacer(1, 6 * mm),

        divider,

        Spacer(1, 2.5 * mm),

        footer,
    ]

    doc.build(story)

    buffer.seek(0)

    return buffer

# =========================================================
# CONFIDENTIAL CASE SUMMARY
# =========================================================

@reports_bp.get(
    "/reports/cases/<int:case_id>/summary.pdf"
)
@roles_required(
    UserRole.STUDENT,
    UserRole.COUNSELOR,
    UserRole.HEAD_COUNSELOR,
    UserRole.ADMIN
)
def case_summary(case_id):

    case = db.session.get(
        CounselingCase,
        case_id,
    )

    user = current_user()

    if not case:

        return error(
            "Case not found.",
            404,
            "not_found",
        )

    if not can_access_case(
        user,
        case,
    ):

        return error(
            "You do not have access to this case.",
            403,
            "forbidden",
        )

    pseudonym = (
        f"STUDENT-{case.student_id:05d}"
    )

    audit(
        "CASE_SUMMARY_GENERATED",
        "case",
        case.id,
        user.id,
    )

    db.session.commit()

    pdf = make_case_summary_pdf(
        case
    )

    return send_file(
        pdf,
        mimetype="application/pdf",
        as_attachment=True,
        download_name=(
            f"case-summary-{case.case_number}.pdf"
        ),
    )

def make_clearance_certificate_pdf(clearance):

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=22 * mm,
        leftMargin=22 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title="Student Exit Clearance Certificate",
        author="University Guidance & Counseling Office",
    )

    # -----------------------------------------------------
    # COLORS
    # -----------------------------------------------------

    purple = colors.HexColor("#6F42C1")
    dark_purple = colors.HexColor("#4F2B78")
    light_purple = colors.HexColor("#F4EEFB")

    dark_text = colors.HexColor("#2F2935")
    gray_text = colors.HexColor("#6F6875")
    border = colors.HexColor("#DDD6E5")
    notice_background = colors.HexColor("#F8F5FB")

    # -----------------------------------------------------
    # STYLES
    # -----------------------------------------------------

    styles = getSampleStyleSheet()

    office_title_style = ParagraphStyle(
        "ClearanceOfficeTitle",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        textColor=dark_text,
        spaceAfter=2,
    )

    office_subtitle_style = ParagraphStyle(
        "ClearanceOfficeSubtitle",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        textColor=gray_text,
    )

    document_title_style = ParagraphStyle(
        "ClearanceDocumentTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=16,
        leading=20,
        alignment=TA_CENTER,
        textColor=dark_purple,
        spaceAfter=0,
    )

    certificate_number_style = ParagraphStyle(
        "ClearanceCertificateNumber",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        alignment=TA_CENTER,
        textColor=gray_text,
    )

    section_title_style = ParagraphStyle(
        "ClearanceSectionTitle",
        parent=styles["Heading3"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=11,
        textColor=dark_purple,
        spaceAfter=0,
    )

    label_style = ParagraphStyle(
        "ClearanceLabel",
        parent=styles["BodyText"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=gray_text,
    )

    value_style = ParagraphStyle(
        "ClearanceValue",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=9.5,
        leading=13,
        textColor=dark_text,
    )

    status_style = ParagraphStyle(
        "ClearanceStatus",
        parent=value_style,
        fontName="Helvetica-Bold",
        textColor=dark_purple,
    )

    notice_title_style = ParagraphStyle(
        "ClearanceNoticeTitle",
        parent=styles["BodyText"],
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=dark_purple,
        spaceAfter=4,
    )

    notice_text_style = ParagraphStyle(
        "ClearanceNoticeText",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12,
        textColor=dark_text,
        alignment=TA_JUSTIFY,
    )

    signature_style = ParagraphStyle(
        "ClearanceSignature",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=8,
        leading=10,
        alignment=TA_CENTER,
        textColor=gray_text,
    )

    footer_style = ParagraphStyle(
        "ClearanceFooter",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=7.5,
        leading=10,
        alignment=TA_CENTER,
        textColor=gray_text,
    )

    # -----------------------------------------------------
    # HEADER
    # -----------------------------------------------------

    gc_logo = Table(
        [[
            Paragraph(
                "<b>GC</b>",
                ParagraphStyle(
                    "ClearanceGCLogo",
                    parent=styles["BodyText"],
                    fontName="Helvetica-Bold",
                    fontSize=19,
                    leading=22,
                    alignment=TA_CENTER,
                    textColor=colors.white,
                ),
            )
        ]],
        colWidths=[19 * mm],
        rowHeights=[19 * mm],
    )

    gc_logo.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                purple,
            ),
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE",
            ),
            (
                "ALIGN",
                (0, 0),
                (-1, -1),
                "CENTER",
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.8,
                purple,
            ),
        ])
    )

    office_text = [
        Paragraph(
            "UNIVERSITY GUIDANCE &amp; COUNSELING OFFICE",
            office_title_style,
        ),
        Paragraph(
            "Guidance and Counseling Management System",
            office_subtitle_style,
        ),
    ]

    header = Table(
        [[gc_logo, office_text]],
        colWidths=[
            24 * mm,
            140 * mm,
        ],
    )

    header.setStyle(
        TableStyle([
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "MIDDLE",
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                0,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                0,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                0,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                0,
            ),
        ])
    )

    divider = Table(
        [[""]],
        colWidths=[166 * mm],
        rowHeights=[1.2 * mm],
    )

    divider.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                purple,
            ),
        ])
    )

    # -----------------------------------------------------
    # STUDENT INFORMATION
    # -----------------------------------------------------

    student = clearance.student

    student_name = student.to_dict()["full_name"]

    student_section_title = Table(
        [[
            Paragraph(
                "STUDENT INFORMATION",
                section_title_style,
            )
        ]],
        colWidths=[166 * mm],
    )

    student_section_title.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                light_purple,
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.5,
                border,
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                6,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                6,
            ),
        ])
    )

    student_data = [
        [
            Paragraph("Student Name", label_style),
            Paragraph(str(student_name or "—"), value_style),
        ],
        [
            Paragraph("Student Number", label_style),
            Paragraph(
                str(student.student_number or "—"),
                value_style,
            ),
        ],
        [
            Paragraph("Program", label_style),
            Paragraph(
                str(student.program or "—"),
                value_style,
            ),
        ],
        [
            Paragraph("Year Level", label_style),
            Paragraph(
                str(student.year_level or "—"),
                value_style,
            ),
        ],
    ]

    student_table = Table(
        student_data,
        colWidths=[
            43 * mm,
            123 * mm,
        ],
    )

    student_table.setStyle(
        TableStyle([
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "TOP",
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.5,
                border,
            ),
            (
                "INNERGRID",
                (0, 0),
                (-1, -1),
                0.35,
                border,
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
        ])
    )

    # -----------------------------------------------------
    # CLEARANCE DETAILS
    # -----------------------------------------------------

    approved_date = (
        format_document_date(clearance.approved_at)
        if clearance.approved_at
        else "—"
    )

    status = (
        clearance.status.value
        if clearance.status
        else "—"
    )

    clearance_section_title = Table(
        [[
            Paragraph(
                "CLEARANCE DETAILS",
                section_title_style,
            )
        ]],
        colWidths=[166 * mm],
    )

    clearance_section_title.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                light_purple,
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.5,
                border,
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                6,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                6,
            ),
        ])
    )

    clearance_data = [
        [
            Paragraph("Academic Year", label_style),
            Paragraph(
                str(clearance.academic_year or "—"),
                value_style,
            ),
        ],
        [
            Paragraph("Clearance Status", label_style),
            Paragraph(
                str(status).replace("_", " ").title(),
                status_style,
            ),
        ],
        [
            Paragraph("Approved Date", label_style),
            Paragraph(
                approved_date,
                value_style,
            ),
        ],
        [
            Paragraph(
                "Exit Questionnaire",
                label_style,
            ),
            Paragraph(
                (
                    "Completed"
                    if clearance.exit_questionnaire_completed
                    else "Not Completed"
                ),
                value_style,
            ),
        ],
        [
            Paragraph(
                "Counseling Requirements",
                label_style,
            ),
            Paragraph(
                (
                    "Completed"
                    if clearance.counseling_requirements_completed
                    else "Not Completed"
                ),
                value_style,
            ),
        ],
        [
            Paragraph(
                "Exit Interview",
                label_style,
            ),
            Paragraph(
                (
                    "Completed"
                    if clearance.exit_interview_completed
                    else "Not Completed"
                ),
                value_style,
            ),
        ],
    ]

    clearance_table = Table(
        clearance_data,
        colWidths=[
            43 * mm,
            123 * mm,
        ],
    )

    clearance_table.setStyle(
        TableStyle([
            (
                "VALIGN",
                (0, 0),
                (-1, -1),
                "TOP",
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.5,
                border,
            ),
            (
                "INNERGRID",
                (0, 0),
                (-1, -1),
                0.35,
                border,
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                8,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
        ])
    )

    # -----------------------------------------------------
    # CERTIFICATION
    # -----------------------------------------------------

    certification = Table(
        [
            [
                Paragraph(
                    "CERTIFICATION",
                    notice_title_style,
                )
            ],
            [
                Paragraph(
                    "This is to certify that the student named above "
                    "has completed the required Guidance and Counseling "
                    "exit-clearance requirements recorded in the system "
                    "for the indicated academic year and has been marked "
                    "CLEARED by the University Guidance and Counseling "
                    "Office.",
                    notice_text_style,
                )
            ],
        ],
        colWidths=[166 * mm],
    )

    certification.setStyle(
        TableStyle([
            (
                "BACKGROUND",
                (0, 0),
                (-1, -1),
                notice_background,
            ),
            (
                "BOX",
                (0, 0),
                (-1, -1),
                0.7,
                purple,
            ),
            (
                "LEFTPADDING",
                (0, 0),
                (-1, -1),
                10,
            ),
            (
                "RIGHTPADDING",
                (0, 0),
                (-1, -1),
                10,
            ),
            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, -1),
                7,
            ),
        ])
    )

    # -----------------------------------------------------
    # SIGNATURE
    # -----------------------------------------------------

    signatures = Table(
        [
            [
                "",
                Paragraph(
                    "____________________________",
                    signature_style,
                ),
            ],
            [
                "",
                Paragraph(
                    "Authorized Guidance Personnel",
                    signature_style,
                ),
            ],
        ],
        colWidths=[
            83 * mm,
            83 * mm,
        ],
    )

    # -----------------------------------------------------
    # FOOTER
    # -----------------------------------------------------

    footer = Paragraph(
        "This is a system-generated document from the "
        "University Guidance &amp; Counseling Management System.",
        footer_style,
    )

    # -----------------------------------------------------
    # BUILD
    # -----------------------------------------------------

    story = [
        header,

        Spacer(1, 3 * mm),

        divider,

        Spacer(1, 4 * mm),

        Paragraph(
            "STUDENT EXIT CLEARANCE CERTIFICATE",
            document_title_style,
        ),

        Spacer(1, 1 * mm),

        Paragraph(
            (
                "Certificate No. "
                f"{clearance.certificate_number or '—'}"
            ),
            certificate_number_style,
        ),

        Spacer(1, 4 * mm),

        KeepTogether([
            student_section_title,
            student_table,
        ]),

        Spacer(1, 4 * mm),

        KeepTogether([
            clearance_section_title,
            clearance_table,
        ]),

        Spacer(1, 4 * mm),

        certification,

        Spacer(1, 7 * mm),

        signatures,

        Spacer(1, 5 * mm),

        divider,

        Spacer(1, 2 * mm),

        footer,
    ]

    doc.build(story)

    buffer.seek(0)

    return buffer

# =========================================================
# STUDENT EXIT CLEARANCE CERTIFICATE
# =========================================================

@reports_bp.get(
    "/reports/clearances/<int:clearance_id>/certificate.pdf"
)
@roles_required(
    UserRole.STUDENT,
    UserRole.HEAD_COUNSELOR,
    UserRole.ADMIN,
    UserRole.STAFF,
)
def clearance_certificate(clearance_id):

    clearance = db.session.get(
        Clearance,
        clearance_id,
    )

    user = current_user()

    if not clearance:

        return error(
            "Clearance record not found.",
            404,
            "not_found",
        )

    if (
        user.role == UserRole.STUDENT
        and clearance.student_id
        != user.student_profile.id
    ):

        return error(
            "You do not have access to this clearance.",
            403,
            "forbidden",
        )

    if (
        clearance.status
        != ClearanceStatus.CLEARED
    ):

        return error(
            "Certificate is unavailable until the student is cleared.",
            409,
            "not_cleared",
        )

    audit(
        "CLEARANCE_CERTIFICATE_GENERATED",
        "clearance",
        clearance.id,
        user.id,
    )

    db.session.commit()

    pdf = make_clearance_certificate_pdf(
        clearance
    )

    return send_file(
        pdf,
        mimetype="application/pdf",
        as_attachment=True,
        download_name=(
            f"clearance-{clearance.certificate_number}.pdf"
        ),
    )